# Generated by Django 4.2.2 on 2023-09-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_price_alter_orderitem_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
