# Generated by Django 4.2.2 on 2023-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_historicalorder_total_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=7),
            preserve_default=False,
        ),
    ]
