# Generated by Django 4.2.1 on 2023-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_key',
        ),
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country_code',
            field=models.CharField(blank=True, default='US', max_length=4),
        ),
    ]
