# Generated by Django 4.2.1 on 2023-10-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalorder_order_total_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(auto_now=True),
        ),
    ]
