# Generated by Django 4.2.1 on 2023-06-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=10),
        ),
    ]
