# Generated by Django 4.2.1 on 2023-10-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_paid_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='shipping_price',
            new_name='shipping_cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_price',
            new_name='shipping_cost',
        ),
    ]
