# Generated by Django 4.2.7 on 2023-12-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_shipping_price_historicalorder_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='created_at',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='updated_at',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
