# Generated by Django 4.2.7 on 2023-12-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_historicalorder_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
    ]
