# Generated by Django 4.2.1 on 2023-06-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_state_province_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='address_line2',
        ),
    ]
