# Generated by Django 4.2.1 on 2023-06-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_address1_order_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
    ]
