# Generated by Django 4.2.2 on 2024-03-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_city_order_city_locality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='sku',
            new_name='stock',
        ),
    ]
