# Generated by Django 4.2.2 on 2023-07-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(default='foo', max_length=12),
            preserve_default=False,
        ),
    ]
