# Generated by Django 4.2.2 on 2023-07-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory_item',
        ),
    ]
