# Generated by Django 4.2.2 on 2023-07-20 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_historicalorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='nomatch', message='Not a valid SKU', regex='A-(?!0)\\d{1,3}(\\.\\d{1,2}x\\d{1,2})?(?(1)[MP]|P?)\\Z|[BHJR]-(?!0)\\d{1,3}\\Z|[DG]-(?!0)\\d{1,3}P?\\Z|L-(?!0)\\d{1,3}[ABC]\\Z|M-(?!0)\\d{1,3}[AEJ]?\\Z|S-[1-9]\\Z')]),
        ),
    ]
