# Generated by Django 4.2.2 on 2023-07-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_historicalorder_kind_order_kind_alter_orderitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_method',
            field=models.CharField(default='USPS parcel', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='USPS parcel', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=5),
            preserve_default=False,
        ),
    ]
