# Generated by Django 4.2.2 on 2023-07-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_productstock_sku'),
        ('orders', '0016_historicalorder_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productstock'),
        ),
    ]
