# Generated by Django 4.2.13 on 2024-07-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_phone_order',
            field=models.BooleanField(default=False),
        ),
    ]
