# Generated by Django 4.2.14 on 2024-08-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_orderitem_stock_orderitem_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
