# Generated by Django 4.2.14 on 2024-09-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('FAST', 'Fast'), ('EXPRESS', 'Express')], max_length=20),
        ),
    ]
