# Generated by Django 4.2.16 on 2024-12-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sku',
        ),
    ]
