# Generated by Django 4.2.16 on 2024-12-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_product_is_set_alter_product_start_date'),
        ('orders', '0023_orderitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalogue.product'),
        ),
    ]
