# Generated by Django 4.2.16 on 2024-12-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_product_is_set_alter_product_start_date'),
        ('orders', '0025_remove_orderitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sku',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalogue.product'),
        ),
    ]
