# Generated by Django 4.2.16 on 2024-12-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_orderitem_sku_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
