# Generated by Django 4.2.16 on 2025-01-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
