# Generated by Django 4.2.16 on 2025-08-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.SmallIntegerField(default=0)),
                ('call_date', models.DateField(default=None)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='orders.order')),
            ],
        ),
    ]
