# Generated by Django 4.2.1 on 2025-10-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='call_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='last_attempt',
        ),
        migrations.AddField(
            model_name='collection',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.SmallIntegerField(default=0)),
                ('date', models.DateField(default=None)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='orders.collection')),
            ],
        ),
    ]
