# Generated by Django 3.2 on 2021-12-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='delivery_method'),
        ),
    ]
