language: python
python:
- '3.8.10'
install:
- pip install -r requirements.txt
script:
- python manage.py test
# blocklist
branches:
  except:
  - development
# safelist
branches:
  only:
  - main
  - release
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &repov
    repo: alexakarpov/htmshop
    branch: main
  bucket: htmshop
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: htmshop
  key: latest.zip
  bundle_type: zip
  application: HTMShopDjango
  deployment_group: HTMShopDG
  region: us-east-1
  on: *repov
script:
  - find . -type d -name '__pycache__' -delete
  #- cd ecommerce/
  - zip -r latest.zip *
  # - zip -u latest.zip ../appspec.yml
  # - zip -u latest.zip ../requirements.txt
  # - zip -u latest.zip ../manage.py
  # - zip -ur latest.zip ../static
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
