[tool.poetry]
name = "htmshop"
version = "0.1.0"
description = ""
authors = ["Alexandre Karpov <alexakarpov@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
gunicorn = "^20"
dj-stripe = "^2.5"
python-dotenv = "^0.19"
django-mptt = "^0.13"
paypalrestsdk = "^1.13"
paypal-checkout-serversdk = "^1"
Pillow = "^9"
black = "^21.12b0"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^3"
isort = "^5.7"
pytest-django = "^4.4"
pytest-factoryboy = "^2.1"
pytest-faker = "^2.0.0"
coverage = "^6.2"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
