---
- name: post-deploy steps
  hosts: htmstore_dev
  become: true
  user: ubuntu

  tasks:
    - name: Extract archive to deployment location
      ansible.builtin.unarchive:
        src: /home/akarpov/htmshop.zip
        dest: /home/storeadmin/htmshop/
        remote_src: true
# secrets
    - name: dotenv file
      copy:
        src: ../secrets/staging.env
        dest: /home/storeadmin/htmshop/.env
        owner: storeadmin
        group: htm

    - name: run migrations
      community.general.django_manage:
        virtualenv: /home/storeadmin/htmshop/venv
        project_path: /home/storeadmin/htmshop
        command: migrate
      environment:
        DJANGO_SETTINGS_MODULE: ecommerce.settings.staging

    - name: static files
      community.general.django_manage:
        virtualenv: /home/storeadmin/htmshop/venv
        project_path: /home/storeadmin/htmshop
        command: collectstatic
      environment:
        DJANGO_SETTINGS_MODULE: ecommerce.settings.staging

    - name: gunicorn service restart
      systemd:
        name: gunicorn.service
        state: restarted
        daemon_reload: yes
