---
- name: post-deploy steps
  hosts: htmstore_dev
  become: true
  user: ubuntu

  tasks:
      #### virtualenv
    - name: create the virtualenv
      command:
        cmd: virtualenv /var/venv -p python3
        creates: '/var/venv'

    - name: venv ownership
      file:
        path: /var/venv
        state: directory
        owner: storeadmin
        group: htm
        mode: 0775

    - name: clear the previous deployment
      file:
        path: /var/htmshop
        state: absent

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/alexakarpov/htmshop.git'
        dest: /var/htmshop/
        version: release
        depth: 1
        force: yes

    - name: Create static_root subdirectory
      file:
        path: /var/htmshop/static_root
        state: directory
        owner: storeadmin
        group: htm
        mode: 0775

    # - name: Extract archive to deployment location
    #   ansible.builtin.unarchive:
    #     src: /tmp/htmshop.zip
    #     dest: /var/htmshop/
    #     remote_src: true

    - name: install dependencies
      pip:
        virtualenv: /var/venv
        requirements: /var/htmshop/requirements.txt

    ### secrets
    - name: dotenv file
      copy:
        src: ../secrets/staging.env
        dest: /var/htmshop/.env
        owner: storeadmin
        group: htm
    ### environment
    - name: run migrations
      community.general.django_manage:
        virtualenv: /var/venv
        project_path: /var/htmshop
        command: migrate
      environment:
        DJANGO_SETTINGS_MODULE: ecommerce.settings.staging

    - name: static files
      community.general.django_manage:
        virtualenv: /var/venv
        project_path: /var/htmshop
        command: collectstatic
      environment:
        DJANGO_SETTINGS_MODULE: ecommerce.settings.staging

    - name: owner of app dir to storeadmin
      file:
        path: /var/htmshop
        state: directory
        recurse: true
        owner: storeadmin
        group: htm

    - name: gunicorn service restart
      systemd:
        name: gunicorn.service
        state: restarted
        daemon_reload: yes
