---
- name: post-deploy steps
  hosts: htmstore_dev
  become: true
  user: ubuntu

  tasks:
    - name: Extract archive to deployment location
      ansible.builtin.unarchive:
        src: /tmp/htmshop.zip
        dest: /var/htmshop/
        remote_src: true

    - name: install dependencies
      pip:
        virtualenv: /var/htmshop/venv
        requirements: /var/htmshop/requirements.txt

    ### secrets
    - name: dotenv file
      copy:
        src: ../secrets/staging.env
        dest: /var/htmshop/.env
        owner: storeadmin
        group: htm
    ### environment
    - name: run migrations
      community.general.django_manage:
        virtualenv: /var/htmshop/venv
        project_path: /var/htmshop
        command: migrate
      environment:
        DJANGO_SETTINGS_MODULE: ecommerce.settings.staging

    - name: static files
      community.general.django_manage:
        virtualenv: /var/htmshop/venv
        project_path: /var/htmshop
        command: collectstatic
      environment:
        DJANGO_SETTINGS_MODULE: ecommerce.settings.staging

    - name: owner of app dir to storeadmin
      file:
        path: /var/htmshop
        state: directory
        recurse: yes
        owner: storeadmin
        group: htm

    - name: gunicorn service restart
      systemd:
        name: gunicorn.service
        state: restarted
        daemon_reload: yes
