import json
import logging
import requests

from dotenv import dotenv_values

from django.conf import settings
from shipengine import ShipEngine
from shipengine.errors import ShipEngineError

from ecommerce.apps.basket.basket import Basket, get_weight

from .choice import rate_to_choice, ShippingChoiceSS

logger = logging.getLogger(__name__)

shipengine = ShipEngine(
    {
        "api_key": settings.SE_API_KEY,
        "page_size": 75,
        "retries": 3,
        "timeout": 10,
    }
)

init_SS_dict = {
    "fromPostalCode": "02445",
    "fromCity": "Brookline",
    "fromState": "MA",
}


def init_SE_shipment_dict():
    return {
        "rate_options": {
            "carrier_ids": [
                settings.USPS_ID,
                settings.FEDEX_ID,
                settings.UPS_ID,
            ],
            "service_codes": [
                # USPS
                # "usps_priority_mail_express",
                # "usps_parcel_select",
                # "usps_first_class_mail",
                # TODO: # "usps_media_mail", # add for books-only basket
            ],
            "package_types": ["package"],
        },
        "shipment": {
            "ship_from": {
                "name": "Shipping department",
                "company_name": "Holy Transfiguration Monastery",
                "phone": "617-734-0608",
                "address_line1": "278 Warren St",
                "city_locality": "Brookline",
                "state_province": "MA",
                "postal_code": "02445",
                "country_code": "US",
                "address_residential_indicator": "yes",
            },
            "ship_to": {},
            "packages": [],
        },
    }


def make_package(basket_dict: dict):
    return {"weight": {"value": get_weight(basket_dict), "unit": "ounce"}}


def make_SE_shipment(basket_dict, address_dict):
    shipment_dict = init_SE_shipment_dict()
    shipment_dict["shipment"]["ship_to"] = address_dict
    shipment_dict["shipment"]["packages"].append(make_package(basket_dict))
    shipment_dict["rate_options"] = {"carrier_ids": ["se-656171"]}
    return shipment_dict


def get_rates(engine, shipment):
    response = engine.get_rates_from_shipment(shipment)
    if response.get("rate_response").get("rates"):
        rates = response.get("rate_response").get("rates")
    else:
        rates = response.get("rate_response").get("invalid_rates")
    logger.warning(f"Rates:\n{rates}")
    return rates


def shipping_choices_SS(basket: Basket, address_dict: dict):
    ss_dict = init_SS_dict
    config = dotenv_values()
    auth = (config["SS_API_KEY"], config["SS_API_SECRET"])
    weight = get_weight(basket)
    logger.warning(f"weight calculated as {weight}")
    ss_dict.update(
        {
            "weight": {"value": weight, "unit": "ounces"},
            "packageCode": "package",
            "carrierCode": "stamps_com",
            "toState": address_dict["state_province"],
            "toCity": address_dict["city_locality"],
            "toPostalCode": address_dict["postal_code"],
            "toCountry": address_dict["country_code"],
        }
    )

    # USPS
    usps_response = requests.post(
        settings.SS_GET_RATES_URL, json=ss_dict, auth=auth
    )

    json_usps = json.loads(usps_response.text)
    choices = []
    for it in json_usps:
        print(it)
        serviceCode = it["serviceCode"]
        cost = it["shipmentCost"]
        choices.append(ShippingChoiceSS(serviceCode, cost))

    # UPS
    ss_dict.update({"carrierCode": "ups"})
    ups_response = requests.post(
        settings.SS_GET_RATES_URL, json=ss_dict, auth=auth
    )

    json_ups = json.loads(ups_response.text)

    for it in json_ups:
        serviceCode = it["serviceCode"]
        cost = it["shipmentCost"]
        choices.append(ShippingChoiceSS(serviceCode, cost))

    return choices


def shipping_choices_SE(basket: Basket, address_d: dict):
    shipment = make_SE_shipment(basket, address_d)

    try:
        if settings.HARDCODE_RATES:
            get_rates_response = HARDCODED_SE_RATES #@FIXME
        else:
            get_rates_response = get_rates(shipengine, shipment)
        logger.warning(f"GET_RATES RETURNED\n{get_rates_response}")
        return list(map(lambda r: rate_to_choice(r), get_rates_response))
    except ShipEngineError as err:
        logger.error("==== ERROR calling ShipEngine")
        logger.error(err.to_json())
        return []


SS_GET_RATES_RESPONSE = [
    {
        "serviceName": "USPS First Class Mail - Large Envelope or Flat",
        "serviceCode": "usps_first_class_mail",
        "shipmentCost": 4.0100,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS First Class Mail - Package",
        "serviceCode": "usps_first_class_mail",
        "shipmentCost": 5.6200,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail - Package",
        "serviceCode": "usps_priority_mail",
        "shipmentCost": 10.0700,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail - Medium Flat Rate Box",
        "serviceCode": "usps_priority_mail",
        "shipmentCost": 15.1900,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail - Small Flat Rate Box",
        "serviceCode": "usps_priority_mail",
        "shipmentCost": 8.7100,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail - Large Flat Rate Box",
        "serviceCode": "usps_priority_mail",
        "shipmentCost": 20.6900,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail - Flat Rate Envelope",
        "serviceCode": "usps_priority_mail",
        "shipmentCost": 8.1800,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail - Flat Rate Padded Envelope",
        "serviceCode": "usps_priority_mail",
        "shipmentCost": 8.9500,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail Express - Package",
        "serviceCode": "usps_priority_mail_express",
        "shipmentCost": 47.2500,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail Express - Flat Rate Envelope",
        "serviceCode": "usps_priority_mail_express",
        "shipmentCost": 26.3500,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Priority Mail Express - Flat Rate Padded Envelope",
        "serviceCode": "usps_priority_mail_express",
        "shipmentCost": 26.8500,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Media Mail - Package",
        "serviceCode": "usps_media_mail",
        "shipmentCost": 4.6300,
        "otherCost": 0.0,
    },
    {
        "serviceName": "USPS Ground Advantage - Package",
        "serviceCode": "usps_ground_advantage",
        "shipmentCost": 5.6200,
        "otherCost": 0.0,
    },
]

# SE rates inside a response:
HARDCODED_SE_RATES = [
    {
        "rate_id": "se-6012937046",
        "rate_type": "shipment",
        "carrier_id": "se-660216",
        "shipping_amount": {"currency": "usd", "amount": 104.58},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 16.21},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Shipping",
                "carrier_billing_code": "BaseServiceCharge",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 104.58},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel Surcharge",
                "carrier_billing_code": "375",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 16.21},
                "billing_source": "Carrier",
            },
        ],
        "zone": None,
        "package_type": "package",
        "delivery_days": 1,
        "guaranteed_service": True,
        "estimated_delivery_date": "2024-10-08T10:30:00Z",
        "carrier_delivery_days": "Tomorrow by 10:30 AM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "UPS Next Day Air®",
        "service_code": "ups_next_day_air",
        "trackable": True,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937047",
        "rate_type": "shipment",
        "carrier_id": "se-660216",
        "shipping_amount": {"currency": "usd", "amount": 134.58},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 20.86},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Shipping",
                "carrier_billing_code": "BaseServiceCharge",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 134.58},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel Surcharge",
                "carrier_billing_code": "375",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 20.86},
                "billing_source": "Carrier",
            },
        ],
        "zone": None,
        "package_type": "package",
        "delivery_days": 1,
        "guaranteed_service": True,
        "estimated_delivery_date": "2024-10-08T08:00:00Z",
        "carrier_delivery_days": "Tomorrow by 08:00 AM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "UPS Next Day Air® Early",
        "service_code": "ups_next_day_air_early_am",
        "trackable": True,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937048",
        "rate_type": "shipment",
        "carrier_id": "se-660216",
        "shipping_amount": {"currency": "usd", "amount": 91.81},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 14.23},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Shipping",
                "carrier_billing_code": "BaseServiceCharge",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 91.81},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel Surcharge",
                "carrier_billing_code": "375",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 14.23},
                "billing_source": "Carrier",
            },
        ],
        "zone": None,
        "package_type": "package",
        "delivery_days": 1,
        "guaranteed_service": True,
        "estimated_delivery_date": "2024-10-08T23:00:00Z",
        "carrier_delivery_days": "Tomorrow by 11:00 PM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "UPS Next Day Air Saver®",
        "service_code": "ups_next_day_air_saver",
        "trackable": True,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937049",
        "rate_type": "shipment",
        "carrier_id": "se-660216",
        "shipping_amount": {"currency": "usd", "amount": 40.92},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 6.34},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Shipping",
                "carrier_billing_code": "BaseServiceCharge",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 40.92},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel Surcharge",
                "carrier_billing_code": "375",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 6.34},
                "billing_source": "Carrier",
            },
        ],
        "zone": None,
        "package_type": "package",
        "delivery_days": 2,
        "guaranteed_service": True,
        "estimated_delivery_date": "2024-10-09T23:00:00Z",
        "carrier_delivery_days": "Wednesday 10/9 by 11:00 PM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "UPS 2nd Day Air®",
        "service_code": "ups_2nd_day_air",
        "trackable": True,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937050",
        "rate_type": "shipment",
        "carrier_id": "se-660216",
        "shipping_amount": {"currency": "usd", "amount": 47.77},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 7.4},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Shipping",
                "carrier_billing_code": "BaseServiceCharge",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 47.77},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel Surcharge",
                "carrier_billing_code": "375",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 7.4},
                "billing_source": "Carrier",
            },
        ],
        "zone": None,
        "package_type": "package",
        "delivery_days": 2,
        "guaranteed_service": True,
        "estimated_delivery_date": "2024-10-09T10:30:00Z",
        "carrier_delivery_days": "Wednesday 10/9 by 10:30 AM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "UPS 2nd Day Air AM®",
        "service_code": "ups_2nd_day_air_am",
        "trackable": True,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937051",
        "rate_type": "shipment",
        "carrier_id": "se-660216",
        "shipping_amount": {"currency": "usd", "amount": 35.96},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 5.57},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Shipping",
                "carrier_billing_code": "BaseServiceCharge",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 35.96},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel Surcharge",
                "carrier_billing_code": "375",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 5.57},
                "billing_source": "Carrier",
            },
        ],
        "zone": None,
        "package_type": "package",
        "delivery_days": 3,
        "guaranteed_service": True,
        "estimated_delivery_date": "2024-10-10T23:00:00Z",
        "carrier_delivery_days": "Thursday 10/10 by 11:00 PM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "UPS 3 Day Select®",
        "service_code": "ups_3_day_select",
        "trackable": True,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937052",
        "rate_type": "shipment",
        "carrier_id": "se-660216",
        "shipping_amount": {"currency": "usd", "amount": 13.38},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 2.21},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Shipping",
                "carrier_billing_code": "BaseServiceCharge",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 13.38},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel Surcharge",
                "carrier_billing_code": "375",
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 2.21},
                "billing_source": "Carrier",
            },
        ],
        "zone": None,
        "package_type": "package",
        "delivery_days": 4,
        "guaranteed_service": True,
        "estimated_delivery_date": "2024-10-11T23:00:00Z",
        "carrier_delivery_days": "Friday 10/11 by 11:00 PM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "UPS® Ground",
        "service_code": "ups_ground",
        "trackable": True,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937054",
        "rate_type": "shipment",
        "carrier_id": "se-660215",
        "shipping_amount": {"currency": "usd", "amount": 11.29},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 0.0},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "shipping",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 11.29},
                "billing_source": "Carrier",
            }
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 2,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-09T00:00:00Z",
        "carrier_delivery_days": "2",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "USPS Priority Mail",
        "service_code": "usps_priority_mail",
        "trackable": True,
        "carrier_code": "stamps_com",
        "carrier_nickname": "ShipEngine Test Account - Stamps.com",
        "carrier_friendly_name": "Stamps.com",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937055",
        "rate_type": "shipment",
        "carrier_id": "se-660215",
        "shipping_amount": {"currency": "usd", "amount": 42.1},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 0.0},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "shipping",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 42.1},
                "billing_source": "Carrier",
            }
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 2,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-09T00:00:00Z",
        "carrier_delivery_days": "2",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "USPS Priority Mail Express",
        "service_code": "usps_priority_mail_express",
        "trackable": True,
        "carrier_code": "stamps_com",
        "carrier_nickname": "ShipEngine Test Account - Stamps.com",
        "carrier_friendly_name": "Stamps.com",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937057",
        "rate_type": "shipment",
        "carrier_id": "se-660215",
        "shipping_amount": {"currency": "usd", "amount": 4.71},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 0.0},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "shipping",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 4.71},
                "billing_source": "Carrier",
            }
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 5,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-12T00:00:00Z",
        "carrier_delivery_days": "5",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "USPS Parcel Select Ground",
        "service_code": "usps_parcel_select",
        "trackable": True,
        "carrier_code": "stamps_com",
        "carrier_nickname": "ShipEngine Test Account - Stamps.com",
        "carrier_friendly_name": "Stamps.com",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937058",
        "rate_type": "shipment",
        "carrier_id": "se-660215",
        "shipping_amount": {"currency": "usd", "amount": 4.71},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 0.0},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "shipping",
                "carrier_description": "shipping",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 4.71},
                "billing_source": "Carrier",
            }
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 5,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-12T00:00:00Z",
        "carrier_delivery_days": "5",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "USPS Ground Advantage",
        "service_code": "usps_ground_advantage",
        "trackable": True,
        "carrier_code": "stamps_com",
        "carrier_nickname": "ShipEngine Test Account - Stamps.com",
        "carrier_friendly_name": "Stamps.com",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937059",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 134.54},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 7.67},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "uncategorized",
                "carrier_description": "Demand Surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.9},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 6.77},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 134.54},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 1,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-08T08:00:00Z",
        "carrier_delivery_days": "Tomorrow by 08:00 AM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx First Overnight®",
        "service_code": "fedex_first_overnight",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937060",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 103.54},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 6.12},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "uncategorized",
                "carrier_description": "Demand Surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.9},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 5.22},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 103.54},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 1,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-08T10:30:00Z",
        "carrier_delivery_days": "Tomorrow by 10:30 AM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx Priority Overnight®",
        "service_code": "fedex_priority_overnight",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937061",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 90.89},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 5.49},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "uncategorized",
                "carrier_description": "Demand Surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.9},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 4.59},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 90.89},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 1,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-08T17:00:00Z",
        "carrier_delivery_days": "Tomorrow by 05:00 PM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx Standard Overnight®",
        "service_code": "fedex_standard_overnight",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937062",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 47.88},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 3.34},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "uncategorized",
                "carrier_description": "Demand Surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.9},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 2.44},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 47.88},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 2,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-09T10:30:00Z",
        "carrier_delivery_days": "Wednesday 10/9 by 10:30 AM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx 2Day® A.M.",
        "service_code": "fedex_2day_am",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937063",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 40.51},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 2.97},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "uncategorized",
                "carrier_description": "Demand Surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.9},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 2.07},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 40.51},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 2,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-09T17:00:00Z",
        "carrier_delivery_days": "Wednesday 10/9 by 05:00 PM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx 2Day®",
        "service_code": "fedex_2day",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937064",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 37.08},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 2.8},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "uncategorized",
                "carrier_description": "Demand Surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.9},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 1.9},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 37.08},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 3,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-10T17:00:00Z",
        "carrier_delivery_days": "Thursday 10/10 by 05:00 PM",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx Express Saver®",
        "service_code": "fedex_express_saver",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937065",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 13.38},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 0.74},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "FedEx Ground Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.74},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 13.38},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 5,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-14T23:59:00Z",
        "carrier_delivery_days": "5",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx Ground®",
        "service_code": "fedex_ground",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "has_warnings",
        "warning_messages": [
            "FedEx may add a Home Delivery Surcharge to this shipment later if this is a residential address."
        ],
        "error_messages": [],
    },
    {
        "rate_id": "se-6012937066",
        "rate_type": "shipment",
        "carrier_id": "se-660217",
        "shipping_amount": {"currency": "usd", "amount": 13.38},
        "insurance_amount": {"currency": "usd", "amount": 0.0},
        "confirmation_amount": {"currency": "usd", "amount": 0.0},
        "other_amount": {"currency": "usd", "amount": 7.12},
        "requested_comparison_amount": {"currency": "usd", "amount": 0.0},
        "rate_details": [
            {
                "rate_detail_type": "delivery",
                "carrier_description": "Residential delivery surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 5.55},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "uncategorized",
                "carrier_description": "Demand Surcharge",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 0.5},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "fuel_charge",
                "carrier_description": "FedEx Ground Fuel",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 1.07},
                "billing_source": "Carrier",
            },
            {
                "rate_detail_type": "shipping",
                "carrier_description": "Total Net Freight",
                "carrier_billing_code": None,
                "carrier_memo": None,
                "amount": {"currency": "usd", "amount": 13.38},
                "billing_source": "Carrier",
            },
        ],
        "zone": 8,
        "package_type": "package",
        "delivery_days": 5,
        "guaranteed_service": False,
        "estimated_delivery_date": "2024-10-14T23:59:00Z",
        "carrier_delivery_days": "5",
        "ship_date": "2024-10-07T00:00:00Z",
        "negotiated_rate": False,
        "service_type": "FedEx Home Delivery®",
        "service_code": "fedex_home_delivery",
        "trackable": True,
        "carrier_code": "fedex",
        "carrier_nickname": "ShipEngine Test Account - FedEx",
        "carrier_friendly_name": "FedEx",
        "validation_status": "valid",
        "warning_messages": [],
        "error_messages": [],
    },
]
