# Generated by Django 4.2.2 on 2023-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
