# Generated by Django 4.0.5 on 2022-08-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Bob', max_length=20, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='Smith', max_length=20, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
