# Generated by Django 4.2.2 on 2023-09-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_trusted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line',
            new_name='address_line1',
        ),
    ]
