# Generated by Django 4.2.2 on 2024-02-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_bookstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='town_city',
            new_name='city_locality',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postcode',
            new_name='postal_code',
        ),
    ]
