# Generated by Django 4.2.16 on 2025-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
