# Generated by Django 4.1.3 on 2023-01-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_remove_productinventory_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Required', max_length=10, unique=True, verbose_name='Product SKU')),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Product Inventory Record',
                'verbose_name_plural': 'Inventory Records',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=55, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'specification',
                'verbose_name_plural': 'Associated Specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=55, unique=True, verbose_name='Product Type name')),
            ],
            options={
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productspecification')),
            ],
            options={
                'verbose_name': 'Product spec',
                'verbose_name_plural': 'Product specs',
            },
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.producttype'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.producttype'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='specifications',
            field=models.ManyToManyField(through='inventory.ProductSpecificationValue', to='inventory.productspecification'),
        ),
    ]
