# Generated by Django 4.2.2 on 2023-07-31 05:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=55, unique=True, verbose_name='Product Type name')),
            ],
            options={
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('spec', models.CharField(blank=True, max_length=20, null=True, verbose_name='specification')),
                ('sku', models.CharField(help_text='Required', max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Not a valid SKU', regex='^A-(?!0)\\d{1,3}(\\.\\d{1,2}x\\d{1,2})?(?(1)[MP]|P?)\\Z|^[BHJR]-(?!0)\\d{1,3}\\Z|^[DG]-(?!0)\\d{1,3}P?\\Z|^L-(?!0)\\d{1,3}[ABC]\\Z|^M-(?!0)\\d{1,3}[AEJ]?\\Z|^S-[1-9]\\Z')], verbose_name='Product SKU')),
                ('restock_point', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('target_amount', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('wrapping_qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Wrapping room stock')),
                ('sanding_qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sanding room stock')),
                ('painting_qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Painting room stock')),
                ('weight', models.DecimalField(decimal_places=2, help_text='ounces', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype')),
            ],
            options={
                'verbose_name': 'Product Stock Record',
                'verbose_name_plural': 'Inventory Stock Records',
            },
        ),
    ]
