# Generated by Django 4.1.3 on 2023-01-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='restock_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
