# Generated by Django 4.2.1 on 2023-08-23 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.CharField(help_text='Required', max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Not a valid SKU', regex='^(A-(?!0)\\d{1,3})\\.(\\d{1,2}x\\d{1,2})?(?(1)[MP]|P?)\\Z|^[BHJR]-(?!0)\\d{1,3}\\Z|^[DG]-(?!0)\\d{1,3}P?\\Z|^L-(?!0)\\d{1,3}[ABC]\\Z|^M-(?!0)\\d{1,3}[AEJ]?\\Z|^S-[1-9]\\Z')], verbose_name='Product SKU'),
        ),
    ]
