# Generated by Django 4.2.2 on 2023-07-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='restock_point',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='target_amount',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
