# Generated by Django 4.2.2 on 2023-08-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=16, help_text='ounces', max_digits=10),
        ),
    ]
