# Generated by Django 4.2.2 on 2023-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_price_alter_stock_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='painting_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Painting room stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='restock_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sanding_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sanding room stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='target_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='ounces', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='wrapping_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wrapping room stock'),
        ),
    ]
