# Generated by Django 4.1.7 on 2023-03-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_quantity_stock_wrapping_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='room',
        ),
        migrations.AlterField(
            model_name='stock',
            name='productinv',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory', verbose_name='Product Inventory'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
