# Generated by Django 4.1.3 on 2023-01-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productinventory_restock_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='weight',
            field=models.FloatField(),
        ),
    ]
