# Generated by Django 4.1.3 on 2023-01-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productinventory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
