# Generated by Django 4.1.7 on 2023-04-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stock_room_alter_stock_productinv_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='painting_qty',
            field=models.IntegerField(default=0, verbose_name='Painting room stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sanding_qty',
            field=models.IntegerField(default=0, verbose_name='Sanding room stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='wrapping_qty',
            field=models.IntegerField(default=0, verbose_name='Wrapping room stock'),
        ),
    ]
