# Generated by Django 4.1.7 on 2023-04-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('orders', '0001_initial'),
        ('inventory', '0004_alter_stock_painting_qty_alter_stock_sanding_qty_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInventory',
            new_name='ProductStock',
        ),
    ]
