# Generated by Django 4.1.3 on 2023-01-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productinventory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='ounces', max_digits=10),
        ),
    ]
