# Generated by Django 4.1.3 on 2023-01-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productinventory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='sku',
            field=models.CharField(help_text='Required', max_length=12, unique=True, verbose_name='Product SKU'),
        ),
    ]
