# Generated by Django 4.1.7 on 2023-04-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_productinventory_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='painting_qty',
            field=models.IntegerField(default=0, verbose_name='Painting room stock'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='sanding_qty',
            field=models.IntegerField(default=0, verbose_name='Sanding room stock'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='wrapping_qty',
            field=models.IntegerField(default=0, verbose_name='Wrapping room stock'),
        ),
    ]
