# Generated by Django 4.1.7 on 2023-04-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productstock_painting_qty_productstock_sanding_qty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
