# Generated by Django 4.1.3 on 2023-01-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productinventory_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='target_amount',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
