# Generated by Django 4.2.14 on 2024-08-30 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stock_painting_qty_alter_stock_restock_point_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock Record', 'verbose_name_plural': 'Stock Records'},
        ),
        migrations.AddField(
            model_name='stock',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.CharField(help_text='Required', max_length=40, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Not a valid SKU', regex='^(A-(?!0)\\d{1,3})(?:\\.(\\d{1,2}x\\d{1,2}))?((?(2)[MP]|P?))\\Z|^([BHJR]-(?!0)\\d{1,3})\\Z|^([DG]-(?!0)\\d{1,3})(P)?\\Z|^(L-(?!0)\\d{1,3})([ABC])\\Z|^(M-(?!0)\\d{1,3})([AEJ])?\\Z|^(S-[1-9])\\Z')], verbose_name='Stock SKU'),
        ),
    ]
