# Generated by Django 4.2.16 on 2025-03-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stock_options_stock_is_set_alter_stock_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Choices order position'),
        ),
    ]
