# Generated by Django 4.1.7 on 2023-04-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Product Stock Record', 'verbose_name_plural': 'Inventory Stock Records'},
        ),
    ]
