# Generated by Django 4.2.16 on 2025-03-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stock_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='order',
        ),
    ]
