# Generated by Django 4.1.6 on 2023-02-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_room_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.productinventory'),
        ),
    ]
