# Generated by Django 4.1.6 on 2023-02-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_productinventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.CharField(default='foo', max_length=20, verbose_name='Room slug'),
            preserve_default=False,
        ),
    ]
