# Generated by Django 4.1.6 on 2023-03-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype'),
        ),
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
    ]
