# Generated by Django 4.2.2 on 2023-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_base',
            field=models.CharField(default='XX-1', max_length=5, unique=True, verbose_name='SKU base'),
            preserve_default=False,
        ),
    ]
