# Generated by Django 4.1.3 on 2023-01-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_productinventory_product_and_more'),
        ('orders', '0002_alter_orderitem_inventory_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInventory',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationValue',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
