# Generated by Django 3.2 on 2022-01-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='some image alt text', help_text='Please add alturnative text', max_length=255, null=True, verbose_name='Alturnative text'),
        ),
    ]
