# Generated by Django 4.2.2 on 2023-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_product_users_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload a product image', max_length=255, upload_to='images/', verbose_name='image'),
        ),
    ]
