# Generated by Django 4.2.2 on 2023-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Flag product as featured', verbose_name='Product is featured'),
        ),
    ]
