# Generated by Django 4.2.2 on 2023-09-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product is active'),
        ),
    ]
