# Generated by Django 4.2.2 on 2023-09-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_productimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='an additional image', max_length=255, null=True, upload_to='images/', verbose_name='Additional image 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, help_text='an additional image', max_length=255, null=True, upload_to='images/', verbose_name='Additional image 2'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
