# Generated by Django 4.2.2 on 2023-09-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_product_image2_product_image3_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', help_text='Upload a product image', max_length=255, upload_to='images/', verbose_name='image'),
        ),
    ]
