# Generated by Django 4.2.2 on 2024-04-06 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 0, 0)),
            preserve_default=False,
        ),
    ]
