# Generated by Django 4.2.14 on 2024-08-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_product_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False, help_text='Flag product as a set', verbose_name='Product is a set'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(blank=True, help_text="When we've started selling this", null=True),
        ),
    ]
